config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categorizations
  resources :categories
  resources :people
  resources :triggers
  resources :lists
  resources :list_inclusions

  root to: 'lists#index'
end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :list
  belongs_to :category
end

app/controllers/categorizations_controller.rb
class CategorizationsController < ApplicationController
  before_action :set_categorization, only: [:show, :edit, :update, :destroy]

  # GET /categorizations
  # GET /categorizations.json
  def index
    @categorizations = Categorization.all
  end

  # GET /categorizations/1
  # GET /categorizations/1.json
  def show
  end

  # GET /categorizations/new
  def new
    @categorization = Categorization.new
  end

  # GET /categorizations/1/edit
  def edit
  end

  # POST /categorizations
  # POST /categorizations.json
  def create
    @categorization = Categorization.new(categorization_params)

    respond_to do |format|
      if @categorization.save
        format.html { redirect_to @categorization, notice: 'Categorization was successfully created.' }
        format.json { render :show, status: :created, location: @categorization }
      else
        format.html { render :new }
        format.json { render json: @categorization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categorizations/1
  # PATCH/PUT /categorizations/1.json
  def update
    respond_to do |format|
      if @categorization.update(categorization_params)
        format.html { redirect_to @categorization, notice: 'Categorization was successfully updated.' }
        format.json { render :show, status: :ok, location: @categorization }
      else
        format.html { render :edit }
        format.json { render json: @categorization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categorizations/1
  # DELETE /categorizations/1.json
  def destroy
    @categorization.destroy
    respond_to do |format|
      format.html { redirect_to categorizations_url, notice: 'Categorization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categorization
      @categorization = Categorization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categorization_params
      params.require(:categorization).permit(:list_id, :category_id)
    end
end

app/helpers/categorizations_helper.rb
module CategorizationsHelper
end

app/views/categorizations/_form.html.erb
<%= form_for(categorization) do |f| %>
  <% if categorization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(categorization.errors.count, "error") %> prohibited this categorization from being saved:</h2>

      <ul>
      <% categorization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :list_id %>
    <%= f.text_field :list_id, value: f.object.list_id || params[:list_id] %>
  </div>

  <div class="field">
    <%= f.label :category_id %>
    <%= f.text_field :category_id, value: f.object.category_id || params[:category_id] %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categorizations/edit.html.erb
<h1>Editing Categorization</h1>

<%= render 'form', categorization: @categorization %>

<%= link_to 'Show', @categorization %> |
<%= link_to 'Back', categorizations_path %>

app/views/categorizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categorizations</h1>

<table>
  <thead>
    <tr>
      <th>List</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categorizations.each do |categorization| %>
      <tr>
        <td><%= categorization.list %></td>
        <td><%= categorization.category %></td>
        <td><%= link_to 'Show', categorization %></td>
        <td><%= link_to 'Edit', edit_categorization_path(categorization) %></td>
        <td><%= link_to 'Destroy', categorization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Categorization', new_categorization_path %>

app/views/categorizations/new.html.erb
<h1>New Categorization</h1>

<%= render 'form', categorization: @categorization %>

<%= link_to 'Back', categorizations_path %>

app/views/categorizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>List:</strong>
  <%= @categorization.list %>
</p>

<p>
  <strong>Category:</strong>
  <%= @categorization.category %>
</p>

<%= link_to 'Edit', edit_categorization_path(@categorization) %> |
<%= link_to 'Back', categorizations_path %>