config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categorizations
  resources :categories
  resources :people
  resources :triggers
  resources :lists
  resources :list_inclusions

  root to: 'lists#index'
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user

  validates_presence_of :name

  has_many :list_inclusions, dependent: :destroy
  has_many :triggers, dependent: :destroy
  has_many :persons, through: :list_inclusions

  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  has_many :familial_list_relationships,
    foreign_key: 'parent_list_id',
    class_name: FamilialListRelationship.name
  has_many :parent_lists, through: :familial_list_relationships
  has_many :child_lists,  through: :familial_list_relationships
  def      sibling_lists; parent_lists.flat_map(&:child_lists); end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @people        = @list.persons.includes(:list_inclusions).distinct
    @triggers      = @list.triggers
    @inclusions    = @list.list_inclusions.includes(:person).order('posted_at desc')
    @parent_lists  = @list.parent_lists
    @child_lists   = @list.child_lists
    @sibling_lists = @list.sibling_lists
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :description)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/panes/_overview.html.erb
<div class="row">
  <div class="col s12">
    <div class="card-panel red">
      <h1 class="display-4">
        <%= list.name %>
      </h1>
      <p class="lead text-justify">
        <%= list.description || 'This is a list managed by Listpump.' %>
      </p>
      <p>
        created <%= time_ago_in_words list.created_at %> ago
      </p>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12 m6">
    <div class="card-panel grey">
      <span class="badge badge-default white-text <%= list.triggers.any? ? 'green' : 'red' %>">
        <%= list.triggers.count %> configured
      </span>
      <h2 class="black-text">Triggers</h2>
      <p class="black-text">
        When someone says something on social media that activates a list's trigger, Listpump will automatically add them to that list.
      </p>
      <p class="center">
        <%= link_to 'Add a trigger', new_trigger_path(list_id: list.id), class: "btn red white-text" %>
      </p>
    </div>
  </div>

  <div class="col s12 m6">
    <div class="card-panel grey">
      <span class="badge badge-default white-text <%= list.persons.any? ? 'green' : 'red' %>">
        <%= list.persons.count %> on this list
      </span>
      <h2 class="black-text">People</h2>
      <p class="black-text">
        When someone says something on social media that activates a list's trigger, Listpump will automatically add them to that list.
        The following 20 persons of interest have been flagged for this list the highest number of times.
      </p>
      <ul>
        <%
          ids_and_counts = ListInclusion.where(list_id: list.id).group(:person_id).order('count_id DESC').limit(20).count(:id)
        %>
        <% ids_and_counts.each do |id, count| %>
          <% person = Person.find(id) %>
          <li>
            <%= link_to person.name, person %>
            (flagged <%= pluralize count, 'time' %>)
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/lists/panes/_people.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Confidence</th>
      <th>Triggered phrases</th>
      <th>Other lists</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% people.order(:name).each do |person| %>
      <tr>
        <td>
          <%= link_to person.name, person %>
          <%= link_to "https://www.reddit.com/u/#{person.name}" do %>
            <%= fa_icon 'reddit' %>
          <% end %>
        </td>
        <td>
          <span class="badge red white-text">
            <%# TODO: Performance code smell %>
            <%= Trigger.where(id: person.list_inclusions.where(list_id: list.id).pluck(:trigger_id)).sum(:confidence) %>
          </span>
        </td>
        <td>
          <ul>
            <% person.list_inclusions.each do |list_inclusion| %>
              <% next unless list_inclusion.list == list %>
              <li>
                "<%= list_inclusion.matched_text %>"
                (<%= link_to list_inclusion.trigger.name, list_inclusion.trigger %>,
                <%= link_to 'source', list_inclusion.source_url %>)
              </li>
            <% end %>
          </ul>
        </td>
        <td>
          <ul>
            <% person.lists.reject { |person_list| person_list == list }.uniq.each do |list| %>
              <li><%= link_to list.name, list %></li>
            <% end %>
          </ul>
        </td>
        <td><%# link_to 'Edit', edit_person_path(person) %></td>
        <td><%# link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/lists/panes/_related_lists.html.erb
<div class="row">
  <div class="col-6">
    <h3>Parent Lists</h3>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Size</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @parent_lists.order(:name).each do |list| %>
          <tr>
            <td><%= link_to list.name, list %></td>
            <td>names <%= pluralize list.persons.count, 'person' %></td>
            <td><%# link_to 'Edit', edit_list_path(list) %></td>
            <td><%# link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-6">
    <h3>Child Lists</h3>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Size</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @child_lists.order(:name).each do |list| %>
          <tr>
            <td><%= link_to list.name, list %></td>
            <td>names <%= pluralize list.persons.count, 'person' %></td>
            <td><%# link_to 'Edit', edit_list_path(list) %></td>
            <td><%# link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<h3>Sibling lists</h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Size</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @sibling_lists.each do |list| %>
      <tr>
        <td><%= link_to list.name, list %></td>
        <td>names <%= pluralize list.persons.count, 'person' %></td>
        <td><%# link_to 'Edit', edit_list_path(list) %></td>
        <td><%# link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/lists/panes/_settings.html.erb
<%= render partial: 'lists/form', locals: { list: list } %>

app/views/lists/panes/_stream.html.erb
<table class="table">
  <thead>
    <tr>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% inclusions.each do |inclusion| %>
      <tr>
        <td>
          <%= form_for inclusion, method: :put  do |f| %>
            <%= f.hidden_field :flagged_invalid_at, value: DateTime.current.to_s %>
            <%= f.submit 'Remove flag', class: 'right btn red black-text' %>
          <% end %>
          
          <p class="white-text">
            <%= link_to inclusion.person.name, inclusion.person %>
              <%= link_to "https://www.reddit.com/u/#{inclusion.person.name}" do %>
                <%= fa_icon 'reddit' %>
              <% end %>
            at
            <%= link_to 'this link', inclusion.source_url %>
            said:
          </p>
          <blockquote><%= inclusion.matched_text %></blockquote>
          <p>
            <small class="grey-text">
              Posted <%= time_ago_in_words inclusion.posted_at %> ago
            </small>
          </p>
          <p>
            Trigger activated:
            <%= link_to inclusion.trigger.name, inclusion.trigger %>
          </p>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/lists/panes/_triggers.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Search Query</th>
      <th>Match Pattern</th>
      <th>Confidence</th>
      <th>Tags</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% triggers.order(:name).each do |trigger| %>
      <tr>
        <td><%= link_to trigger.name, trigger %></td>
        <td><span class="badge blue white-text"><%= trigger.search_query %></span></td>
        <td><span class="badge blue white-text">/<%= trigger.pattern %>/</span></td>
        <td><span class="badge red white-text"><%= trigger.confidence %></span></td>
        <td>
          <% trigger.user_tags_applied.each do |tag_text| %>
            <span class="badge grey white-text"><%= tag_text %></span>
          <% end %>
        </td>
        <td>
          <%= form_for trigger, remote: true, format: 'json' do |f| %>
            <%= f.check_box :enabled, data: { toggle: 'toggle', onstyle: 'success', size: 'small' }, class: 'js-submit-on-change' %>
          <% end %>
        </td>
        <td><%= link_to 'Edit', edit_trigger_path(trigger) %></td>
        <td><%= link_to 'Destroy', trigger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="row">
  <div class="col-sm-12">
    <div class="card-panel grey darken-1 white-text">
      <h2>
        Add <%= triggers.any? ? 'another' : 'a' %> trigger
      </h2>
      <div>
        <%= render partial: 'triggers/form', locals: { trigger: Trigger.new(list: @list) } %>
      </div>
    </div>
  </div>
</div>