config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categorizations
  resources :categories
  resources :people
  resources :triggers
  resources :lists
  resources :list_inclusions

  root to: 'lists#index'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categorizations
  has_many :lists, through: :categorizations
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>
  <%= link_to 'New Category', new_category_path, class: 'btn btn-primary float-right' %>
  Categories
</h1>

<div class="row">
  <% @categories.each do |category| %>
    <div class="col-sm-3 card">
      <div class="card-block">
        <h4 class="card-title"><%= category.name %></h4>
        <p class="card-text">
          <%= link_to pluralize(category.lists.count, 'list'), category %>
        </p>
        <%= link_to 'Edit', edit_category_path(category), class: 'card-link' %>
        <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: 'card-link' %>
      </div>
    </div>
  <% end %>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h1>
  <%= link_to 'Add a list', new_categorization_path(category_id: @category.id), class: 'btn btn-primary float-right' %>
  <%= link_to 'Edit category', edit_category_path(@category), class: 'btn float-right' %>
  <%= @category.name %>
</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Size</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @category.lists.order(:name).each do |list| %>
      <tr>
        <td><%= link_to list.name, list %></td>
        <td>names <%= pluralize list.persons.count, 'person' %></td>
        <td><%# link_to 'Edit', edit_list_path(list) %></td>
        <td><%# link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>